### ISSUE TITLE
ZecWallet Lite 1.4.2 Create New Wallet Crashes

### ISSUE THREAD

**Issue by briansorahan** [zecwalletco/zecwallet-mobile#41]
![Screenshot_20210310-090826](https://user-images.githubusercontent.com/544737/110816874-59790f80-8251-11eb-945f-8b470900c6ed.png)
See screenshot for phone model/number (hope it contains everything you need, otherwise LMK)
When I hit “Create New Wallet” the application crashes almost immediately.
Any help is greatly appreciated!

**Comment by briansorahan** [comment]
Here is the actual phone info:
```
Model: moto g7 play
Hardware version: PVT
Model Number (SKU): XT1952-4
```

**Comment by briansorahan** [comment]
I plan to debug this with Android Studio sometime in the next week or so. Hopefully it bears fruit.
I've never done Android development before so will be a great learning experience.

**Comment by briansorahan** [comment]
@adityapk00 I went through the steps in the readme
```
cd rust/android
./build.sh
cd ../..
yarn install
npx react-native start
```

I got this:
```
To reload the app press "r"
To open developer menu press "d"

warn No apps connected. Sending "devMenu" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Opening developer menu...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Volumes/BetterFS/github.com/briansorahan/zecwallet-mobile/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
```

I pressed `d` btw ^ and had my android device connected via USB.
Any suggestions on how to proceed?

FWIW:
```
➜  zecwallet-mobile git:(master) ulimit
unlimited
```
